---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 5555, host: 5555}]
    - ["forwarded_port", {guest: 5556, host: 5556}]
    - ["forwarded_port", {guest: 4567, host: 4567}]

provisioner:
  name: chef_zero

platforms:
  - name: opscode-ubuntu-14.04
  # - name: opscode-centos-6.6

suites:
  - name: default
    run_list:
      - recipe[riemann2::server]
      - recipe[riemann2::dash]
      - recipe[riemann2::tools]
    attributes:
