---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: opscode-ubuntu-14.04
  - name: opscode-centos-6.6

suites:
  - name: default
    run_list:
      - recipe[riemann::server]
    attributes:
