AllCops:
  Exclude:
    - Guardfile
    - 'vendor/**/*'
AlignParameters:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Max: 200
HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - Rakefile
    - 'spec/**/*'
    - 'test/**/*'
# Don't fail on whitespace between method names and arguments
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
